---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    console:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: console
        stream: ext://sys.stdout

#    info_file_handler:
#        class: logging.handlers.RotatingFileHandler
#        level: INFO
#        formatter: simple
#        filename: ./log/info.log #think: how to use relative path! 
#        maxBytes: 20971520 # 20MB
#        backupCount: 20
#        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: ./log/error.log #think: how to use relative path! 
        maxBytes: 20971520 # 20MB
        backupCount: 20
        encoding: utf8

loggers:
    util:
        level: INFO
        handlers: [console, error_file_handler]
        propagate: no      
        
    controller:
        level: DEBUG
        handlers: [console, error_file_handler]
        propagate: no     

root:
    level: INFO 
    handlers: [console, error_file_handler]
